name: delivery_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^10.5.0
  flutter_bloc: ^7.0.0
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_database: ^10.2.5
  firebase_messaging: ^14.6.7
  cloud_firestore: ^4.9.0
  flutter_local_notifications: ^15.1.1
  ntp: ^2.0.0
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.1
  shared_preferences: ^2.2.0
  http: ^1.1.0
  image_picker: ^1.0.2
  bloc: ^7.0.0
  uuid: ^3.0.7
  page_transition: ^2.0.9
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  location: ^5.0.3
  geocoding: ^2.0.0
  google_maps_flutter: ^2.0.6
  flutter_spinkit: ^5.2.0
  connectivity: ^3.0.6
  share_plus: ^7.1.0
  platform: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  flutter_driver:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/images/
   - assets/lang/ar.json
   - assets/lang/en.json
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Arvo
      fonts:
        - asset: assets/fonts/Arvo-Regular.ttf
        - asset: assets/fonts/Arvo-Italic.ttf
          style: italic
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
